-- =====================================================
-- 高频词数据：考研英语一 + 考研英语二
-- =====================================================
SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';

-- ──────────── 考研英语一 KAOYAN1（level=3，学术抽象） ────────────
INSERT IGNORE INTO tb_word (word, phonetic, meaning, example_en, example_zh, level, category, source, created_at, updated_at) VALUES
('acknowledge', '/əkˈnɒlɪdʒ/',        'v.承认；致谢', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('advocate',    '/ˈædvəkeɪt/',        'v.提倡 n.拥护者', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('allocate',    '/ˈæləkeɪt/',         'v.分配；拨给', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('analogy',     '/əˈnælədʒi/',        'n.类比；类推', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('apparatus',   '/ˌæpəˈreɪtəs/',      'n.器械；装置；机构', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('arbitrary',   '/ˈɑːbɪtrəri/',       'adj.任意的；专断的', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('assimilate',  '/əˈsɪməleɪt/',       'v.吸收；同化', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('assumption',  '/əˈsʌmpʃn/',         'n.假定；承担', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('attribute',   '/əˈtrɪbjuːt/',       'v.归因于 n.属性', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('authoritative','/ɔːˈθɒrɪtətɪv/',    'adj.权威的；官方的', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('autonomous',  '/ɔːˈtɒnəməs/',       'adj.自治的；自主的', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('barren',      '/ˈbærən/',           'adj.贫瘠的；不育的', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('batch',       '/bætʃ/',             'n.一批；一组', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('breach',      '/briːtʃ/',           'n./v.违反；破裂', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('breakdown',   '/ˈbreɪkdaʊn/',       'n.故障；崩溃；分解', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('breed',       '/briːd/',            'v.繁殖；培育 n.品种', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('burden',      '/ˈbɜːdn/',           'n.负担 v.使负重', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('casual',      '/ˈkæʒuəl/',          'adj.随意的；偶然的', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('cease',       '/siːs/',             'v.停止；终止', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('characterize','/ˈkærəktəraɪz/',     'v.以…为特征；描述', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('charter',     '/ˈtʃɑːtə/',          'n.宪章；特许 v.包租', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('cite',        '/saɪt/',             'v.引用；引证', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('clarify',     '/ˈklærəfaɪ/',        'v.澄清；阐明', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('clash',       '/klæʃ/',             'n./v.冲突；碰撞', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('clause',      '/klɔːz/',            'n.从句；条款', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('climax',      '/ˈklaɪmæks/',        'n.高潮；顶点', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('cling',       '/klɪŋ/',             'v.紧握；依附；坚持', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('cluster',     '/ˈklʌstə/',          'n.簇；群 v.聚集', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('coherent',    '/kəʊˈhɪərənt/',      'adj.连贯的；条理清楚的', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('collaborate', '/kəˈlæbəreɪt/',      'v.合作；协作', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('commemorate', '/kəˈmeməreɪt/',      'v.纪念；庆祝', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('commentary',  '/ˈkɒməntri/',        'n.评论；解说', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('commission',  '/kəˈmɪʃn/',          'n.委员会；佣金 v.委托', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('commit',      '/kəˈmɪt/',           'v.承诺；犯（罪）；投入', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('commonplace', '/ˈkɒmənpleɪs/',      'adj.平凡的 n.寻常事', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('commute',     '/kəˈmjuːt/',         'v.通勤；减刑', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('compact',     '/kəmˈpækt/',         'adj.紧凑的 n.协议', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('comparable',  '/ˈkɒmpərəbl/',       'adj.可比较的；比得上的', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('comparative', '/kəmˈpærətɪv/',      'adj.比较的；相对的', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('compel',      '/kəmˈpel/',          'v.强迫；迫使', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('competent',   '/ˈkɒmpɪtənt/',       'adj.有能力的；胜任的', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('complement',  '/ˈkɒmplɪment/',      'v./n.补充；补足', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('component',   '/kəmˈpəʊnənt/',      'n.组成部分；零件', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('compound',    '/ˈkɒmpaʊnd/',        'n.化合物 adj.复合的', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('comprehensive','/ˌkɒmprɪˈhensɪv/',  'adj.全面的；综合的', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('comprise',    '/kəmˈpraɪz/',        'v.包含；由…组成', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('concede',     '/kənˈsiːd/',         'v.承认；让步', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('condemn',     '/kənˈdem/',          'v.谴责；判刑', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('confine',     '/kənˈfaɪn/',         'v.限制；禁闭 n.界限', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW()),
('conform',     '/kənˈfɔːm/',         'v.遵守；符合', '', '', 3, 'KAOYAN1', 'system', NOW(), NOW());

INSERT IGNORE INTO tb_word_book_item (book_id, word_id)
SELECT b.id, w.id FROM tb_word w JOIN tb_word_book b ON b.code='KAOYAN1'
WHERE w.word IN ('acknowledge','advocate','allocate','analogy','apparatus','arbitrary','assimilate','assumption','attribute','authoritative',
'autonomous','barren','batch','breach','breakdown','breed','burden','casual','cease','characterize',
'charter','cite','clarify','clash','clause','climax','cling','cluster','coherent','collaborate',
'commemorate','commentary','commission','commit','commonplace','commute','compact','comparable','comparative','compel',
'competent','complement','component','compound','comprehensive','comprise','concede','condemn','confine','conform');

-- ──────────── 考研英语二 KAOYAN2（level=2，商务/应用） ────────────
INSERT IGNORE INTO tb_word (word, phonetic, meaning, example_en, example_zh, level, category, source, created_at, updated_at) VALUES
('agenda',      '/əˈdʒendə/',          'n.议程；日程', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('asset',       '/ˈæset/',             'n.资产；有价值的人或物', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('audit',       '/ˈɔːdɪt/',            'n./v.审计；审核', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('bargain',     '/ˈbɑːɡən/',           'n.便宜货；协议 v.讨价还价', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('brand',       '/brænd/',             'n.品牌；商标', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('bulk',        '/bʌlk/',              'n.大块；大量 adj.大批的', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('commercial',  '/kəˈmɜːʃl/',          'adj.商业的 n.商业广告', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('commodity',   '/kəˈmɒdəti/',         'n.商品；日用品', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('competitive', '/kəmˈpetətɪv/',       'adj.竞争的；有竞争力的', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('consumer',    '/kənˈsjuːmə/',        'n.消费者；顾客', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('contract',    '/ˈkɒntrækt/',         'n.合同 v.订约；收缩', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('corporation', '/ˌkɔːpəˈreɪʃn/',       'n.公司；法人', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('coupon',      '/ˈkuːpɒn/',           'n.优惠券；票券', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('deficit',     '/ˈdefɪsɪt/',          'n.赤字；亏损；不足', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('deposit',     '/dɪˈpɒzɪt/',          'v./n.存款；押金；存放', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('entrepreneur','/ˌɒntrəprəˈnɜː/',      'n.企业家；创业者', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('estate',      '/ɪˈsteɪt/',           'n.房地产；财产', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('expense',     '/ɪkˈspens/',          'n.花费；开支', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('export',      '/ɪkˈspɔːt/',          'v./n.出口；输出', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('franchise',   '/ˈfræntʃaɪz/',        'n.特许经营权；加盟', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('freight',     '/freɪt/',             'n.货运；运费', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('incentive',   '/ɪnˈsentɪv/',         'n.激励；动机', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('inflation',   '/ɪnˈfleɪʃn/',         'n.通货膨胀', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('invoice',     '/ˈɪnvɔɪs/',           'n.发票；账单', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('lease',       '/liːs/',              'n.租约 v.出租', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('liability',   '/ˌlaɪəˈbɪləti/',      'n.责任；负债；累赘', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('logistics',   '/ləˈdʒɪstɪks/',       'n.物流；后勤', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('margin',      '/ˈmɑːdʒɪn/',          'n.利润；边缘；余地', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('merchant',    '/ˈmɜːtʃənt/',         'n.商人 adj.商业的', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('mortgage',    '/ˈmɔːɡɪdʒ/',          'n.抵押贷款 v.抵押', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('negotiate',   '/nɪˈɡəʊʃieɪt/',       'v.谈判；协商', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('outlet',      '/ˈaʊtlet/',           'n.折扣店；出口；经销店', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('pension',     '/ˈpenʃn/',            'n.养老金；退休金', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('portfolio',   '/pɔːtˈfəʊliəʊ/',       'n.投资组合；作品集', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('premium',     '/ˈpriːmiəm/',         'n.保险费；溢价 adj.高端的', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('procurement', '/prəˈkjʊəmənt/',      'n.采购；获得', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('profit',      '/ˈprɒfɪt/',           'n.利润 v.获益', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('promotion',   '/prəˈməʊʃn/',         'n.晋升；促销；推广', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('prospect',    '/ˈprɒspekt/',         'n.前景；可能性', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('quota',       '/ˈkwəʊtə/',           'n.配额；限额', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('recession',   '/rɪˈseʃn/',           'n.经济衰退；萧条', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('retail',      '/ˈriːteɪl/',          'n./v.零售', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('revenue',     '/ˈrevənjuː/',         'n.收入；税收', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('shipment',    '/ˈʃɪpmənt/',          'n.装运；货物', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('sponsor',     '/ˈspɒnsə/',           'v.赞助 n.赞助商', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('subsidy',     '/ˈsʌbsədi/',          'n.补贴；津贴', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('surplus',     '/ˈsɜːpləs/',          'n.剩余；盈余 adj.过剩的', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('tariff',      '/ˈtærɪf/',            'n.关税；价目表', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('transaction', '/trænˈzækʃn/',        'n.交易；业务', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('turnover',    '/ˈtɜːnəʊvə/',         'n.营业额；人员流动率', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('vendor',      '/ˈvendə/',            'n.卖主；小贩；供应商', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('voucher',     '/ˈvaʊtʃə/',           'n.代金券；凭证', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW()),
('wholesale',   '/ˈhəʊlseɪl/',         'n./adj.批发（的）', '', '', 2, 'KAOYAN2', 'system', NOW(), NOW());

INSERT IGNORE INTO tb_word_book_item (book_id, word_id)
SELECT b.id, w.id FROM tb_word w JOIN tb_word_book b ON b.code='KAOYAN2'
WHERE w.word IN ('agenda','asset','audit','bargain','brand','bulk','commercial','commodity','competitive','consumer',
'contract','corporation','coupon','deficit','deposit','entrepreneur','estate','expense','export','franchise',
'freight','incentive','inflation','invoice','lease','liability','logistics','margin','merchant','mortgage',
'negotiate','outlet','pension','portfolio','premium','procurement','profit','promotion','prospect','quota',
'recession','retail','revenue','shipment','sponsor','subsidy','surplus','tariff','transaction','turnover',
'vendor','voucher','wholesale');
