-- =====================================================
-- 高频词数据：中考词汇 + 日常高频词（基础，level=1）
-- 单词跨书重复时靠 uk_word 唯一索引 INSERT IGNORE 去重
-- =====================================================
SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';

-- ──────────── 中考词汇 ZHONGKAO ────────────
INSERT IGNORE INTO tb_word (word, phonetic, meaning, example_en, example_zh, level, category, source, created_at, updated_at) VALUES
('accept',      '/əkˈsept/',            'v.接受；认可', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('achieve',     '/əˈtʃiːv/',            'v.实现；达到；完成', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('address',     '/əˈdres/',             'n.地址；演讲 v.向…讲话', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('advice',      '/ədˈvaɪs/',            'n.忠告；建议', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('afford',      '/əˈfɔːd/',             'v.买得起；承担得起', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('afraid',      '/əˈfreɪd/',            'adj.害怕的；担心的', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('agree',       '/əˈɡriː/',             'v.同意；赞成', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('allow',       '/əˈlaʊ/',              'v.允许；准许', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('among',       '/əˈmʌŋ/',              'prep.在…之中', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('angry',       '/ˈæŋɡri/',             'adj.生气的；愤怒的', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('attention',   '/əˈtenʃn/',            'n.注意；专心', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('believe',     '/bɪˈliːv/',            'v.相信；认为', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('borrow',      '/ˈbɒrəʊ/',             'v.借入；借用', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('brave',       '/breɪv/',              'adj.勇敢的', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('bright',      '/braɪt/',              'adj.明亮的；聪明的', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('calendar',    '/ˈkælɪndə/',           'n.日历；日程表', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('careful',     '/ˈkeəfl/',             'adj.小心的；仔细的', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('celebrate',   '/ˈselɪbreɪt/',         'v.庆祝', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('century',     '/ˈsentʃəri/',          'n.世纪；百年', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('chance',      '/tʃɑːns/',             'n.机会；可能性', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('choose',      '/tʃuːz/',              'v.选择；挑选', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('communicate', '/kəˈmjuːnɪkeɪt/',      'v.交流；沟通', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('compare',     '/kəmˈpeə/',            'v.比较；对照', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('consider',    '/kənˈsɪdə/',           'v.考虑；认为', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('continue',    '/kənˈtɪnjuː/',         'v.继续；持续', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('courage',     '/ˈkʌrɪdʒ/',            'n.勇气；胆量', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('culture',     '/ˈkʌltʃə/',            'n.文化', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('custom',      '/ˈkʌstəm/',            'n.习俗；习惯', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('decide',      '/dɪˈsaɪd/',            'v.决定；下决心', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('describe',    '/dɪˈskraɪb/',          'v.描述；形容', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('develop',     '/dɪˈveləp/',           'v.发展；开发', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('dialogue',    '/ˈdaɪəlɒɡ/',           'n.对话', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('diary',       '/ˈdaɪəri/',            'n.日记', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('discover',    '/dɪˈskʌvə/',           'v.发现', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('discuss',     '/dɪˈskʌs/',            'v.讨论', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('disease',     '/dɪˈziːz/',            'n.疾病', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('distance',    '/ˈdɪstəns/',           'n.距离', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('doubt',       '/daʊt/',               'n./v.怀疑', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('during',      '/ˈdjʊərɪŋ/',           'prep.在…期间', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('eager',       '/ˈiːɡə/',              'adj.渴望的；热切的', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('education',   '/ˌedʒuˈkeɪʃn/',        'n.教育', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('encourage',   '/ɪnˈkʌrɪdʒ/',          'v.鼓励', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('energy',      '/ˈenədʒi/',            'n.能量；精力', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('environment', '/ɪnˈvaɪrənmənt/',      'n.环境', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('especially',  '/ɪˈspeʃəli/',          'adv.特别；尤其', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('experience',  '/ɪkˈspɪəriəns/',       'n.经验；经历 v.经历', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('explain',     '/ɪkˈspleɪn/',          'v.解释；说明', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('foreign',     '/ˈfɒrən/',             'adj.外国的', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('government',  '/ˈɡʌvənmənt/',         'n.政府', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW()),
('imagine',     '/ɪˈmædʒɪn/',           'v.想象', '', '', 1, 'ZHONGKAO', 'system', NOW(), NOW());

INSERT IGNORE INTO tb_word_book_item (book_id, word_id)
SELECT b.id, w.id FROM tb_word w JOIN tb_word_book b ON b.code='ZHONGKAO'
WHERE w.word IN ('accept','achieve','address','advice','afford','afraid','agree','allow','among','angry',
'attention','believe','borrow','brave','bright','calendar','careful','celebrate','century','chance',
'choose','communicate','compare','consider','continue','courage','culture','custom','decide','describe',
'develop','dialogue','diary','discover','discuss','disease','distance','doubt','during','eager',
'education','encourage','energy','environment','especially','experience','explain','foreign','government','imagine');

-- ──────────── 日常高频词 DAILY ────────────
INSERT IGNORE INTO tb_word (word, phonetic, meaning, example_en, example_zh, level, category, source, created_at, updated_at) VALUES
('apologize',   '/əˈpɒlədʒaɪz/',        'v.道歉', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('appointment', '/əˈpɔɪntmənt/',        'n.约会；预约', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('appetite',    '/ˈæpɪtaɪt/',           'n.食欲；胃口', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('bakery',      '/ˈbeɪkəri/',           'n.面包店', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('battery',     '/ˈbætri/',             'n.电池', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('booking',     '/ˈbʊkɪŋ/',             'n.预订', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('cafeteria',   '/ˌkæfəˈtɪəriə/',       'n.自助餐厅', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('cashier',     '/kæˈʃɪə/',             'n.收银员', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('charger',     '/ˈtʃɑːdʒə/',           'n.充电器', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('crowded',     '/ˈkraʊdɪd/',           'adj.拥挤的', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('customer',    '/ˈkʌstəmə/',           'n.顾客', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('delivery',    '/dɪˈlɪvəri/',          'n.递送；快递', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('dentist',     '/ˈdentɪst/',           'n.牙医', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('department',  '/dɪˈpɑːtmənt/',        'n.部门；百货区域', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('discount',    '/ˈdɪskaʊnt/',          'n.折扣', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('elevator',    '/ˈelɪveɪtə/',          'n.电梯', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('emergency',   '/ɪˈmɜːdʒənsi/',        'n.紧急情况', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('expensive',   '/ɪkˈspensɪv/',         'adj.昂贵的', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('facility',    '/fəˈsɪləti/',          'n.设施；设备', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('grocery',     '/ˈɡrəʊsəri/',          'n.食品杂货', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('guarantee',   '/ˌɡærənˈtiː/',         'v./n.保证；担保', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('haircut',     '/ˈheəkʌt/',            'n.理发', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('ingredient',  '/ɪnˈɡriːdiənt/',       'n.原料；成分', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('luggage',     '/ˈlʌɡɪdʒ/',            'n.行李', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('neighborhood','/ˈneɪbəhʊd/',          'n.街区；社区', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('pharmacy',    '/ˈfɑːməsi/',           'n.药店；药房', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('receipt',     '/rɪˈsiːt/',            'n.收据', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('recommend',   '/ˌrekəˈmend/',         'v.推荐', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('reservation', '/ˌrezəˈveɪʃn/',        'n.预订；预约', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('schedule',    '/ˈʃedjuːl/',           'n.时间表；日程 v.安排', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('souvenir',    '/ˌsuːvəˈnɪə/',         'n.纪念品', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('subway',      '/ˈsʌbweɪ/',            'n.地铁', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('supermarket', '/ˈsuːpəmɑːkɪt/',       'n.超市', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('laundry',     '/ˈlɔːndri/',           'n.洗衣店；待洗衣物', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('menu',        '/ˈmenjuː/',            'n.菜单', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('waiter',      '/ˈweɪtə/',             'n.（男）服务员', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('traffic',     '/ˈtræfɪk/',            'n.交通', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('passenger',   '/ˈpæsɪndʒə/',          'n.乘客', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('direction',   '/dəˈrekʃn/',           'n.方向；指引', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('intersection','/ˌɪntəˈsekʃn/',        'n.十字路口', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('comfortable', '/ˈkʌmftəbl/',          'adj.舒适的', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('convenient',  '/kənˈviːniənt/',       'adj.方便的', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('refund',      '/ˈriːfʌnd/',           'n./v.退款', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('queue',       '/kjuː/',               'n.队伍 v.排队', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('southern',    '/ˈsʌðən/',             'adj.南方的', '', '', 1, 'DAILY', 'system', NOW(), NOW()),
('umbrella',    '/ʌmˈbrelə/',           'n.雨伞', '', '', 1, 'DAILY', 'system', NOW(), NOW());

INSERT IGNORE INTO tb_word_book_item (book_id, word_id)
SELECT b.id, w.id FROM tb_word w JOIN tb_word_book b ON b.code='DAILY'
WHERE w.word IN ('apologize','appointment','appetite','bakery','battery','booking','cafeteria','cashier','charger','crowded',
'customer','delivery','dentist','department','discount','elevator','emergency','expensive','facility','grocery',
'guarantee','haircut','ingredient','luggage','neighborhood','pharmacy','receipt','recommend','reservation','schedule',
'souvenir','subway','supermarket','laundry','menu','waiter','traffic','passenger','direction','intersection',
'comfortable','convenient','refund','queue','southern','umbrella');
