-- =====================================================
-- 高频词数据：雅思 IELTS + 托福 TOEFL
-- =====================================================
SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';

-- ──────────── 雅思 IELTS（level=2~3，教育/社会/生活） ────────────
INSERT IGNORE INTO tb_word (word, phonetic, meaning, example_en, example_zh, level, category, source, created_at, updated_at) VALUES
('adequate',    '/ˈædɪkwət/',          'adj.充足的；胜任的', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('adjust',      '/əˈdʒʌst/',           'v.调整；适应', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('adolescent',  '/ˌædəˈlesnt/',        'n.青少年 adj.青春期的', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('adverse',     '/ˈædvɜːs/',           'adj.不利的；有害的', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('aesthetic',   '/iːsˈθetɪk/',         'adj.美学的；审美的', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('affluent',    '/ˈæfluənt/',          'adj.富裕的；丰富的', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('alter',       '/ˈɔːltə/',            'v.改变；更改', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('ample',       '/ˈæmpl/',             'adj.充足的；丰富的', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('appliance',   '/əˈplaɪəns/',         'n.器具；家用电器', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('approximate', '/əˈprɒksɪmət/',       'adj.大约的 v.接近', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('arena',       '/əˈriːnə/',           'n.竞技场；舞台', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('assemble',    '/əˈsembl/',           'v.集合；组装', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('assure',      '/əˈʃʊə/',             'v.保证；使确信', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('astronomy',   '/əˈstrɒnəmi/',        'n.天文学', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('attendance',  '/əˈtendəns/',         'n.出席；出勤', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('attorney',    '/əˈtɜːni/',           'n.律师；代理人', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('auction',     '/ˈɔːkʃn/',            'n./v.拍卖', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('aviation',    '/ˌeɪviˈeɪʃn/',        'n.航空；航空业', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('barrier',     '/ˈbæriə/',            'n.障碍；屏障', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('behalf',      '/bɪˈhɑːf/',           'n.代表；利益', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('bibliography','/ˌbɪbliˈɒɡrəfi/',      'n.参考书目；文献', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('blend',       '/blend/',             'v.混合 n.混合物', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('boom',        '/buːm/',              'n./v.繁荣；激增', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('border',      '/ˈbɔːdə/',            'n.边界；边境', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('brochure',    '/ˈbrəʊʃə/',           'n.小册子；宣传册', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('browse',      '/braʊz/',             'v.浏览；放牧', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('bubble',      '/ˈbʌbl/',             'n.气泡；泡沫', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('bulletin',    '/ˈbʊlətɪn/',          'n.公告；简报', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('bundle',      '/ˈbʌndl/',            'n.捆；束；包', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('cabinet',     '/ˈkæbɪnət/',          'n.橱柜；内阁', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('canal',       '/kəˈnæl/',            'n.运河；水道', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('carriage',    '/ˈkærɪdʒ/',           'n.车厢；马车；运费', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('carve',       '/kɑːv/',              'v.雕刻；切开', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('census',      '/ˈsensəs/',           'n.人口普查；统计', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('cereal',      '/ˈsɪəriəl/',          'n.谷物；谷类食物', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('chamber',     '/ˈtʃeɪmbə/',          'n.房间；议院；腔', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('chaos',       '/ˈkeɪɒs/',            'n.混乱；混沌', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('charity',     '/ˈtʃærəti/',          'n.慈善；慈善机构', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('chef',        '/ʃef/',               'n.主厨；厨师', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('chunk',       '/tʃʌŋk/',             'n.厚块；大量', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('circuit',     '/ˈsɜːkɪt/',           'n.电路；环道', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('civilian',    '/səˈvɪliən/',         'n.平民 adj.民用的', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('coalition',   '/ˌkəʊəˈlɪʃn/',        'n.联盟；联合', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('coastal',     '/ˈkəʊstl/',           'adj.沿海的；海岸的', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('cognitive',   '/ˈkɒɡnətɪv/',         'adj.认知的；认识的', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('collapse',    '/kəˈlæps/',           'v./n.倒塌；崩溃', '', '', 2, 'IELTS', 'system', NOW(), NOW()),
('colony',      '/ˈkɒləni/',           'n.殖民地；群落', '', '', 3, 'IELTS', 'system', NOW(), NOW()),
('column',      '/ˈkɒləm/',            'n.圆柱；专栏；列', '', '', 2, 'IELTS', 'system', NOW(), NOW());

INSERT IGNORE INTO tb_word_book_item (book_id, word_id)
SELECT b.id, w.id FROM tb_word w JOIN tb_word_book b ON b.code='IELTS'
WHERE w.word IN ('adequate','adjust','adolescent','adverse','aesthetic','affluent','alter','ample','appliance','approximate',
'arena','assemble','assure','astronomy','attendance','attorney','auction','aviation','barrier','behalf',
'bibliography','blend','boom','border','brochure','browse','bubble','bulletin','bundle','cabinet',
'canal','carriage','carve','census','cereal','chamber','chaos','charity','chef','chunk',
'circuit','civilian','coalition','coastal','cognitive','collapse','colony','column');

-- ──────────── 托福 TOEFL（level=3，学术/学科） ────────────
INSERT IGNORE INTO tb_word (word, phonetic, meaning, example_en, example_zh, level, category, source, created_at, updated_at) VALUES
('archaeology', '/ˌɑːkiˈɒlədʒi/',      'n.考古学', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('architecture','/ˈɑːkɪtektʃə/',       'n.建筑学；建筑风格', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('botany',      '/ˈbɒtəni/',           'n.植物学', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('carbohydrate','/ˌkɑːbəʊˈhaɪdreɪt/',  'n.碳水化合物', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('civilization','/ˌsɪvəlaɪˈzeɪʃn/',    'n.文明；文化', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('classify',    '/ˈklæsɪfaɪ/',         'v.分类；归类', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('comet',       '/ˈkɒmɪt/',            'n.彗星', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('composition', '/ˌkɒmpəˈzɪʃn/',       'n.构成；作品；作文', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('continental', '/ˌkɒntɪˈnentl/',      'adj.大陆的；大洲的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('decompose',   '/ˌdiːkəmˈpəʊz/',      'v.分解；腐烂', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('density',     '/ˈdensəti/',          'n.密度；浓度', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('deplete',     '/dɪˈpliːt/',          'v.耗尽；使枯竭', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('dinosaur',    '/ˈdaɪnəsɔː/',         'n.恐龙', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('ecology',     '/iˈkɒlədʒi/',         'n.生态学；生态', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('ecosystem',   '/ˈiːkəʊsɪstəm/',      'n.生态系统', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('empirical',   '/ɪmˈpɪrɪkl/',         'adj.经验主义的；实证的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('entity',      '/ˈentəti/',           'n.实体；独立存在物', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('equation',    '/ɪˈkweɪʒn/',          'n.方程式；等式', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('erosion',     '/ɪˈrəʊʒn/',           'n.侵蚀；腐蚀', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('evacuate',    '/ɪˈvækjueɪt/',        'v.疏散；撤离', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('evaporate',   '/ɪˈvæpəreɪt/',        'v.蒸发；消失', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('evoke',       '/ɪˈvəʊk/',            'v.唤起；引起', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('exceptional', '/ɪkˈsepʃənl/',        'adj.杰出的；例外的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('expel',       '/ɪkˈspel/',           'v.驱逐；开除', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('extrapolate', '/ɪkˈstræpəleɪt/',     'v.推断；外推', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('fauna',       '/ˈfɔːnə/',            'n.动物群；动物区系', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('finite',      '/ˈfaɪnaɪt/',          'adj.有限的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('fluid',       '/ˈfluːɪd/',           'n.流体 adj.流动的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('foliage',     '/ˈfəʊliɪdʒ/',         'n.叶子（总称）', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('forage',      '/ˈfɒrɪdʒ/',           'v.觅食 n.饲料', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('funnel',      '/ˈfʌnl/',             'n.漏斗；漏斗云', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('gaseous',     '/ˈɡæsiəs/',           'adj.气态的；气体的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('geometry',    '/dʒiˈɒmətri/',        'n.几何学', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('glacier',     '/ˈɡlæsiə/',           'n.冰川；冰河', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('granite',     '/ˈɡrænɪt/',           'n.花岗岩', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('grazing',     '/ˈɡreɪzɪŋ/',          'n.放牧；草场', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('herbivore',   '/ˈhɜːbɪvɔː/',         'n.食草动物', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('hypothesis',  '/haɪˈpɒθəsɪs/',       'n.假设；假说', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('ignite',      '/ɪɡˈnaɪt/',           'v.点燃；引发', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('indigenous',  '/ɪnˈdɪdʒənəs/',       'adj.本土的；土著的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('infrastructure','/ˈɪnfrəstrʌktʃə/',  'n.基础设施', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('isotope',     '/ˈaɪsətəʊp/',         'n.同位素', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('kinetic',     '/kɪˈnetɪk/',          'adj.运动的；动力的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('latitude',    '/ˈlætɪtjuːd/',        'n.纬度；自由', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('lava',        '/ˈlɑːvə/',            'n.熔岩；火山岩', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('linguistic',  '/lɪŋˈɡwɪstɪk/',       'adj.语言的；语言学的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('longitude',   '/ˈlɒŋɡɪtjuːd/',       'n.经度', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('mammal',      '/ˈmæml/',             'n.哺乳动物', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('manipulate',  '/məˈnɪpjuleɪt/',      'v.操纵；操作', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('mechanism',   '/ˈmekənɪzəm/',        'n.机制；机械装置', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('medieval',    '/ˌmediˈiːvl/',        'adj.中世纪的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('membrane',    '/ˈmembreɪn/',         'n.膜；薄膜', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('metabolism',  '/məˈtæbəlɪzəm/',      'n.新陈代谢', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('meteorology', '/ˌmiːtiəˈrɒlədʒi/',   'n.气象学', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('migrate',     '/maɪˈɡreɪt/',         'v.迁徙；移居', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('molecule',    '/ˈmɒlɪkjuːl/',        'n.分子', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('monsoon',     '/ˌmɒnˈsuːn/',         'n.季风；雨季', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('nebula',      '/ˈnebjələ/',          'n.星云', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('negligible',  '/ˈneɡlɪdʒəbl/',       'adj.可忽略的；微不足道的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('nocturnal',   '/nɒkˈtɜːnl/',         'adj.夜间活动的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('nomadic',     '/nəʊˈmædɪk/',         'adj.游牧的；流浪的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('opaque',      '/əʊˈpeɪk/',           'adj.不透明的；难懂的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('optimal',     '/ˈɒptɪml/',           'adj.最佳的；最理想的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('organism',    '/ˈɔːɡənɪzəm/',        'n.生物体；有机体', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('oscillate',   '/ˈɒsɪleɪt/',          'v.振荡；摆动', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('overlap',     '/ˌəʊvəˈlæp/',         'v./n.重叠；交叠', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('oxide',       '/ˈɒksaɪd/',           'n.氧化物', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('paradigm',    '/ˈpærədaɪm/',         'n.范式；典范；范例', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('paradox',     '/ˈpærədɒks/',         'n.悖论；自相矛盾', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('parasite',    '/ˈpærəsaɪt/',         'n.寄生虫；寄生生物', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('particle',    '/ˈpɑːtɪkl/',          'n.颗粒；微粒；粒子', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('pathology',   '/pəˈθɒlədʒi/',        'n.病理学；病变', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('penetrate',   '/ˈpenɪtreɪt/',        'v.穿透；渗透', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('peripheral',  '/pəˈrɪfərəl/',        'adj.外围的；次要的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('perpetual',   '/pəˈpetʃuəl/',        'adj.永久的；不断的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('pesticide',   '/ˈpestɪsaɪd/',        'n.杀虫剂；农药', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('photosynthesis','/ˌfəʊtəʊˈsɪnθəsɪs/','n.光合作用', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('plateau',     '/ˈplætəʊ/',           'n.高原；平稳期', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('plausible',   '/ˈplɔːzəbl/',         'adj.貌似可信的；花言巧语的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('polar',       '/ˈpəʊlə/',            'adj.极地的；两极的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('pollen',      '/ˈpɒlən/',            'n.花粉', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('pollinate',   '/ˈpɒlɪneɪt/',         'v.给…授粉', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('predator',    '/ˈpredətə/',          'n.捕食者；掠食者', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('precipitate', '/prɪˈsɪpɪteɪt/',      'v.使突然发生 n.沉淀物', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('prevalent',   '/ˈprevələnt/',        'adj.流行的；普遍的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('prototype',   '/ˈprəʊtətaɪp/',       'n.原型；雏形', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('radioactive', '/ˌreɪdiəʊˈæktɪv/',    'adj.放射性的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('sediment',    '/ˈsedɪmənt/',         'n.沉积物；沉淀', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('simultaneous','/ˌsɪmlˈteɪniəs/',     'adj.同时的；同步的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('species',     '/ˈspiːʃiːz/',         'n.物种；种类', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('specimen',    '/ˈspesɪmən/',         'n.标本；样本', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('tectonic',    '/tekˈtɒnɪk/',         'adj.构造的；建筑的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('terrestrial', '/təˈrestriəl/',       'adj.陆地的；地球的', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('topography',  '/təˈpɒɡrəfi/',        'n.地形学；地貌', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('velocity',    '/vəˈlɒsəti/',         'n.速度；速率', '', '', 3, 'TOEFL', 'system', NOW(), NOW()),
('volcanic',    '/vɒlˈkænɪk/',         'adj.火山的；猛烈的', '', '', 3, 'TOEFL', 'system', NOW(), NOW());

INSERT IGNORE INTO tb_word_book_item (book_id, word_id)
SELECT b.id, w.id FROM tb_word w JOIN tb_word_book b ON b.code='TOEFL'
WHERE w.word IN ('archaeology','architecture','botany','carbohydrate','civilization','classify','comet','composition','continental','decompose',
'density','deplete','dinosaur','ecology','ecosystem','empirical','entity','equation','erosion','evacuate',
'evaporate','evoke','exceptional','expel','extrapolate','fauna','finite','fluid','foliage','forage',
'funnel','gaseous','geometry','glacier','granite','grazing','herbivore','hypothesis','ignite','indigenous',
'infrastructure','isotope','kinetic','latitude','lava','linguistic','longitude','mammal','manipulate','mechanism',
'medieval','membrane','metabolism','meteorology','migrate','molecule','monsoon','nebula','negligible','nocturnal',
'nomadic','opaque','optimal','organism','oscillate','overlap','oxide','paradigm','paradox','parasite',
'particle','pathology','penetrate','peripheral','perpetual','pesticide','photosynthesis','plateau','plausible','polar',
'pollen','pollinate','predator','precipitate','prevalent','prototype','radioactive','sediment','simultaneous','species',
'specimen','tectonic','terrestrial','topography','velocity','volcanic');
