-- =====================================================
-- 高频词数据：四级补充 + 六级补充
-- =====================================================
SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';

-- ──────────── 四级补充 CET4（level=2） ────────────
INSERT IGNORE INTO tb_word (word, phonetic, meaning, example_en, example_zh, level, category, source, created_at, updated_at) VALUES
('accomplish',  '/əˈkʌmplɪʃ/',         'v.完成；实现', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('accumulate',  '/əˈkjuːmjəleɪt/',     'v.积累；积聚', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('advertise',   '/ˈædvətaɪz/',         'v.做广告；宣传', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('agency',      '/ˈeɪdʒənsi/',         'n.代理处；机构', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('analyze',     '/ˈænəlaɪz/',          'v.分析', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('anxiety',     '/æŋˈzaɪəti/',         'n.焦虑；忧虑', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('applicant',   '/ˈæplɪkənt/',         'n.申请人', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('artificial',  '/ˌɑːtɪˈfɪʃl/',        'adj.人工的；人造的', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('assign',      '/əˈsaɪn/',            'v.分配；指派', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('athlete',     '/ˈæθliːt/',           'n.运动员', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('attain',      '/əˈteɪn/',            'v.达到；获得', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('award',       '/əˈwɔːd/',            'v.授予 n.奖品', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('benefit',     '/ˈbenɪfɪt/',          'n.益处 v.有益于', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('billion',     '/ˈbɪljən/',           'num.十亿', '', '', 1, 'CET-4', 'system', NOW(), NOW()),
('biology',     '/baɪˈɒlədʒi/',        'n.生物学', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('budget',      '/ˈbʌdʒɪt/',           'n.预算 v.编预算', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('calculate',   '/ˈkælkjuleɪt/',       'v.计算；估算', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('capacity',    '/kəˈpæsəti/',         'n.容量；能力', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('carbon',      '/ˈkɑːbən/',           'n.碳', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('circumstance','/ˈsɜːkəmstəns/',      'n.环境；情况', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('citizen',     '/ˈsɪtɪzn/',           'n.公民；市民', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('colleague',   '/ˈkɒliːɡ/',           'n.同事', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('community',   '/kəˈmjuːnəti/',       'n.社区；团体', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('compete',     '/kəmˈpiːt/',          'v.竞争；比赛', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('complain',    '/kəmˈpleɪn/',         'v.抱怨；投诉', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('complex',     '/ˈkɒmpleks/',         'adj.复杂的 n.综合体', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('concentrate', '/ˈkɒnsntreɪt/',       'v.集中；专心', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('concept',     '/ˈkɒnsept/',          'n.概念；观念', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('confident',   '/ˈkɒnfɪdənt/',        'adj.自信的；确信的', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('conflict',    '/ˈkɒnflɪkt/',         'n./v.冲突；矛盾', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('consequence', '/ˈkɒnsɪkwəns/',       'n.结果；后果', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('contribute',  '/kənˈtrɪbjuːt/',      'v.贡献；捐献；促成', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('convince',    '/kənˈvɪns/',          'v.说服；使确信', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('cooperate',   '/kəʊˈɒpəreɪt/',       'v.合作；协作', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('critical',    '/ˈkrɪtɪkl/',          'adj.批评的；关键的', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('current',     '/ˈkʌrənt/',           'adj.当前的 n.水流；电流', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('debate',      '/dɪˈbeɪt/',           'n./v.辩论；争论', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('decade',      '/ˈdekeɪd/',           'n.十年', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('decline',     '/dɪˈklaɪn/',          'v./n.下降；衰退；谢绝', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('define',      '/dɪˈfaɪn/',           'v.定义；界定', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('deliver',     '/dɪˈlɪvə/',           'v.递送；发表；接生', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('demonstrate', '/ˈdemənstreɪt/',      'v.证明；演示；示威', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('determine',   '/dɪˈtɜːmɪn/',         'v.决定；查明', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('disaster',    '/dɪˈzɑːstə/',         'n.灾难', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('distinguish', '/dɪˈstɪŋɡwɪʃ/',       'v.区分；辨别', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('distribute',  '/dɪˈstrɪbjuːt/',      'v.分配；分发', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('efficient',   '/ɪˈfɪʃnt/',           'adj.高效的', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('eliminate',   '/ɪˈlɪmɪneɪt/',        'v.消除；淘汰', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('emotion',     '/ɪˈməʊʃn/',           'n.情感；情绪', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('emphasize',   '/ˈemfəsaɪz/',         'v.强调', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('establish',   '/ɪˈstæblɪʃ/',         'v.建立；确立', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('evidence',    '/ˈevɪdəns/',          'n.证据', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('expand',      '/ɪkˈspænd/',          'v.扩大；膨胀', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('expose',      '/ɪkˈspəʊz/',          'v.暴露；揭露', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('financial',   '/faɪˈnænʃl/',         'adj.财政的；金融的', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('function',    '/ˈfʌŋkʃn/',           'n.功能 v.运转', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('fundamental', '/ˌfʌndəˈmentl/',      'adj.基本的；根本的', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('generate',    '/ˈdʒenəreɪt/',        'v.产生；发电', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('generous',    '/ˈdʒenərəs/',         'adj.慷慨的；大量的', '', '', 2, 'CET-4', 'system', NOW(), NOW()),
('genuine',     '/ˈdʒenjuɪn/',         'adj.真正的；真诚的', '', '', 2, 'CET-4', 'system', NOW(), NOW());

INSERT IGNORE INTO tb_word_book_item (book_id, word_id)
SELECT b.id, w.id FROM tb_word w JOIN tb_word_book b ON b.code='CET4'
WHERE w.word IN ('accomplish','accumulate','advertise','agency','analyze','anxiety','applicant','artificial','assign','athlete',
'attain','award','benefit','billion','biology','budget','calculate','capacity','carbon','circumstance',
'citizen','colleague','community','compete','complain','complex','concentrate','concept','confident','conflict',
'consequence','contribute','convince','cooperate','critical','current','debate','decade','decline','define',
'deliver','demonstrate','determine','disaster','distinguish','distribute','efficient','eliminate','emotion','emphasize',
'establish','evidence','expand','expose','financial','function','fundamental','generate','generous','genuine');

-- ──────────── 六级补充 CET6（level=3） ────────────
INSERT IGNORE INTO tb_word (word, phonetic, meaning, example_en, example_zh, level, category, source, created_at, updated_at) VALUES
('abolish',     '/əˈbɒlɪʃ/',           'v.废除；废止', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('accommodate', '/əˈkɒmədeɪt/',        'v.容纳；提供住宿；适应', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('ambiguous',   '/æmˈbɪɡjuəs/',        'adj.模棱两可的；含糊的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('anonymous',   '/əˈnɒnɪməs/',         'adj.匿名的；无名的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('applaud',     '/əˈplɔːd/',           'v.鼓掌；称赞', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('articulate',  '/ɑːˈtɪkjuleɪt/',      'adj.表达清晰的 v.清楚表达', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('assert',      '/əˈsɜːt/',            'v.断言；主张；维护', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('assurance',   '/əˈʃʊərəns/',         'n.保证；信心', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('authentic',   '/ɔːˈθentɪk/',         'adj.真正的；真实可靠的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('autonomy',    '/ɔːˈtɒnəmi/',         'n.自治；自主权', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('bankrupt',    '/ˈbæŋkrʌpt/',         'adj.破产的 v.使破产', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('betray',      '/bɪˈtreɪ/',           'v.背叛；泄露', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('bewilder',    '/bɪˈwɪldə/',          'v.使迷惑；使不知所措', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('bizarre',     '/bɪˈzɑː/',            'adj.古怪的；奇异的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('bleak',       '/bliːk/',             'adj.阴冷的；黯淡的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('boost',       '/buːst/',             'v./n.促进；推动；增强', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('boycott',     '/ˈbɔɪkɒt/',           'v./n.抵制', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('breakthrough','/ˈbreɪkθruː/',        'n.突破；突破性进展', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('bureaucracy', '/bjʊəˈrɒkrəsi/',      'n.官僚机构；官僚主义', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('cater',       '/ˈkeɪtə/',            'v.迎合；提供饮食', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('catastrophe', '/kəˈtæstrəfi/',       'n.大灾难；大祸', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('cherish',     '/ˈtʃerɪʃ/',           'v.珍惜；怀有', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('chronic',     '/ˈkrɒnɪk/',           'adj.慢性的；长期的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('circulation', '/ˌsɜːkjəˈleɪʃn/',     'n.循环；流通；发行量', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('coincide',    '/ˌkəʊɪnˈsaɪd/',       'v.同时发生；一致；重合', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('collide',     '/kəˈlaɪd/',           'v.碰撞；冲突', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('commence',    '/kəˈmens/',           'v.开始；着手', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('compatible',  '/kəmˈpætəbl/',        'adj.兼容的；相容的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('compensate',  '/ˈkɒmpenseɪt/',       'v.补偿；赔偿', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('compile',     '/kəmˈpaɪl/',          'v.编纂；编译', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('compulsory',  '/kəmˈpʌlsəri/',       'adj.强制的；义务的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('conceive',    '/kənˈsiːv/',          'v.构想；设想；怀孕', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('confidential','/ˌkɒnfɪˈdenʃl/',       'adj.机密的；保密的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('conform',     '/kənˈfɔːm/',          'v.遵守；符合；顺应', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('consensus',   '/kənˈsensəs/',        'n.一致；共识', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('conserve',    '/kənˈsɜːv/',          'v.保护；节约 n.蜜饯', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('constrain',   '/kənˈstreɪn/',        'v.限制；约束', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('contemplate', '/ˈkɒntəmpleɪt/',      'v.沉思；考虑；凝视', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('contradict',  '/ˌkɒntrəˈdɪkt/',      'v.反驳；与…矛盾', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('correlate',   '/ˈkɒrəleɪt/',         'v.相互关联', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('corrupt',     '/kəˈrʌpt/',           'adj.腐败的 v.腐蚀', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('counterpart', '/ˈkaʊntəpɑːt/',       'n.对应的人或物', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('crucial',     '/ˈkruːʃl/',           'adj.至关重要的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('cultivate',   '/ˈkʌltɪveɪt/',        'v.培养；耕作', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('cumulative',  '/ˈkjuːmjələtɪv/',     'adj.累积的；渐增的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('curb',        '/kɜːb/',              'v./n.抑制；控制', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('deduce',      '/dɪˈdjuːs/',          'v.推断；演绎', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('deficiency',  '/dɪˈfɪʃnsi/',         'n.缺乏；不足；缺陷', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('deprive',     '/dɪˈpraɪv/',          'v.剥夺；使丧失', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('descend',     '/dɪˈsend/',           'v.下降；下来', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('deteriorate', '/dɪˈtɪəriəreɪt/',     'v.恶化；变坏', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('diminish',    '/dɪˈmɪnɪʃ/',          'v.减少；降低；贬低', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('discriminate','/dɪˈskrɪmɪneɪt/',     'v.歧视；区别对待', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('disperse',    '/dɪˈspɜːs/',          'v.分散；驱散', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('distort',     '/dɪˈstɔːt/',          'v.扭曲；歪曲', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('divert',      '/daɪˈvɜːt/',          'v.转移；使改道；娱乐', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('dominant',    '/ˈdɒmɪnənt/',         'adj.占主导的；显性的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('drastic',     '/ˈdræstɪk/',          'adj.激烈的；剧烈的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('dwell',       '/dwel/',              'v.居住；详述', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('eloquent',    '/ˈeləkwənt/',         'adj.雄辩的；有口才的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('endanger',    '/ɪnˈdeɪndʒə/',        'v.危及；使遭危险', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('endeavor',    '/ɪnˈdevə/',           'v./n.努力；尽力', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('endure',      '/ɪnˈdjʊə/',           'v.忍受；持久', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('enhance',     '/ɪnˈhɑːns/',          'v.提高；增强', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('essence',     '/ˈesns/',             'n.本质；精髓', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('exempt',      '/ɪɡˈzempt/',          'adj.被豁免的 v.免除', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('exhaust',     '/ɪɡˈzɔːst/',          'v.使筋疲力尽；耗尽', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('explicit',    '/ɪkˈsplɪsɪt/',        'adj.明确的；清楚的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('extinct',     '/ɪkˈstɪŋkt/',         'adj.灭绝的；熄灭的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('fabricate',   '/ˈfæbrɪkeɪt/',        'v.捏造；制造', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('facilitate',  '/fəˈsɪlɪteɪt/',       'v.促进；使便利', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('feasible',    '/ˈfiːzəbl/',          'adj.可行的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('fluctuate',   '/ˈflʌktʃueɪt/',       'v.波动；起伏', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('formidable',  '/ˈfɔːmɪdəbl/',        'adj.强大的；令人敬畏的', '', '', 3, 'CET-6', 'system', NOW(), NOW()),
('fragile',     '/ˈfrædʒaɪl/',         'adj.易碎的；脆弱的', '', '', 3, 'CET-6', 'system', NOW(), NOW());

INSERT IGNORE INTO tb_word_book_item (book_id, word_id)
SELECT b.id, w.id FROM tb_word w JOIN tb_word_book b ON b.code='CET6'
WHERE w.word IN ('abolish','accommodate','ambiguous','anonymous','applaud','articulate','assert','assurance','authentic','autonomy',
'bankrupt','betray','bewilder','bizarre','bleak','boost','boycott','breakthrough','bureaucracy','cater',
'catastrophe','cherish','chronic','circulation','coincide','collide','commence','compatible','compensate','compile',
'compulsory','conceive','confidential','conform','consensus','conserve','constrain','contemplate','contradict','correlate',
'corrupt','counterpart','crucial','cultivate','cumulative','curb','deduce','deficiency','deprive','descend',
'deteriorate','diminish','discriminate','disperse','distort','divert','dominant','drastic','dwell','eloquent',
'endanger','endeavor','endure','enhance','essence','exempt','exhaust','explicit','extinct','fabricate',
'facilitate','feasible','fluctuate','formidable','fragile');
