-- =====================================================
-- 高频词数据：高考词汇（level=1~2）
-- =====================================================
SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';

INSERT IGNORE INTO tb_word (word, phonetic, meaning, example_en, example_zh, level, category, source, created_at, updated_at) VALUES
('abandon',     '/əˈbændən/',          'v.放弃；抛弃；遗弃', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('absolute',    '/ˈæbsəluːt/',         'adj.绝对的；完全的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('absorb',      '/əbˈzɔːb/',           'v.吸收；吸引', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('abstract',    '/ˈæbstrækt/',         'adj.抽象的 n.摘要', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('academic',    '/ˌækəˈdemɪk/',        'adj.学术的；学院的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('account',     '/əˈkaʊnt/',           'n.账户；描述 v.解释', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('accurate',    '/ˈækjərət/',          'adj.精确的；准确的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('acquire',     '/əˈkwaɪə/',           'v.获得；习得', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('adapt',       '/əˈdæpt/',            'v.适应；改编', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('admire',      '/ədˈmaɪə/',           'v.钦佩；欣赏', '', '', 1, 'GAOKAO', 'system', NOW(), NOW()),
('admit',       '/ədˈmɪt/',            'v.承认；准许进入', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('adopt',       '/əˈdɒpt/',            'v.采用；收养', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('advance',     '/ədˈvɑːns/',          'v./n.前进；进步', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('affect',      '/əˈfekt/',            'v.影响；感动', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('aggressive',  '/əˈɡresɪv/',          'adj.好斗的；有进取心的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('alternative', '/ɔːlˈtɜːnətɪv/',      'n.可供选择的事物 adj.可供替代的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('annual',      '/ˈænjuəl/',           'adj.每年的；年度的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('apparent',    '/əˈpærənt/',          'adj.明显的；表面上的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('appeal',      '/əˈpiːl/',            'v./n.呼吁；吸引；上诉', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('appreciate',  '/əˈpriːʃieɪt/',       'v.欣赏；感激；增值', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('appropriate', '/əˈprəʊpriət/',       'adj.适当的；恰当的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('approve',     '/əˈpruːv/',           'v.批准；赞成', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('arrange',     '/əˈreɪndʒ/',          'v.安排；整理', '', '', 1, 'GAOKAO', 'system', NOW(), NOW()),
('assess',      '/əˈses/',             'v.评估；评定', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('assist',      '/əˈsɪst/',            'v.帮助；协助', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('associate',   '/əˈsəʊʃieɪt/',        'v.联系；交往 n.同事', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('assume',      '/əˈsjuːm/',           'v.假定；承担', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('atmosphere',  '/ˈætməsfɪə/',         'n.大气；气氛', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('attach',      '/əˈtætʃ/',            'v.系；附上；使依恋', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('attempt',     '/əˈtempt/',           'v./n.尝试；企图', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('attitude',    '/ˈætɪtjuːd/',         'n.态度；看法', '', '', 1, 'GAOKAO', 'system', NOW(), NOW()),
('available',   '/əˈveɪləbl/',         'adj.可获得的；有空的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('average',     '/ˈævərɪdʒ/',          'adj.平均的；普通的 n.平均数', '', '', 1, 'GAOKAO', 'system', NOW(), NOW()),
('aware',       '/əˈweə/',             'adj.意识到的；知道的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('balance',     '/ˈbæləns/',           'n.平衡 v.使平衡', '', '', 1, 'GAOKAO', 'system', NOW(), NOW()),
('behave',      '/bɪˈheɪv/',           'v.表现；举止', '', '', 1, 'GAOKAO', 'system', NOW(), NOW()),
('beneficial',  '/ˌbenɪˈfɪʃl/',        'adj.有益的；有利的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('blame',       '/bleɪm/',             'v.责备 n.责任', '', '', 1, 'GAOKAO', 'system', NOW(), NOW()),
('boundary',    '/ˈbaʊndri/',          'n.边界；界限', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('brilliant',   '/ˈbrɪliənt/',         'adj.杰出的；灿烂的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('campaign',    '/kæmˈpeɪn/',          'n.运动；战役 v.参加活动', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('candidate',   '/ˈkændɪdət/',         'n.候选人；应试者', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('capable',     '/ˈkeɪpəbl/',          'adj.有能力的；能干的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('career',      '/kəˈrɪə/',            'n.职业；事业', '', '', 1, 'GAOKAO', 'system', NOW(), NOW()),
('cautious',    '/ˈkɔːʃəs/',           'adj.谨慎的；小心的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('ceremony',    '/ˈserəməni/',         'n.典礼；仪式', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('challenge',   '/ˈtʃælɪndʒ/',         'n./v.挑战', '', '', 1, 'GAOKAO', 'system', NOW(), NOW()),
('characteristic','/ˌkærəktəˈrɪstɪk/', 'n.特征 adj.典型的', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('claim',       '/kleɪm/',             'v./n.声称；要求；索赔', '', '', 2, 'GAOKAO', 'system', NOW(), NOW()),
('combine',     '/kəmˈbaɪn/',          'v.结合；联合', '', '', 2, 'GAOKAO', 'system', NOW(), NOW());

INSERT IGNORE INTO tb_word_book_item (book_id, word_id)
SELECT b.id, w.id FROM tb_word w JOIN tb_word_book b ON b.code='GAOKAO'
WHERE w.word IN ('abandon','absolute','absorb','abstract','academic','account','accurate','acquire','adapt','admire',
'admit','adopt','advance','affect','aggressive','alternative','annual','apparent','appeal','appreciate',
'appropriate','approve','arrange','assess','assist','associate','assume','atmosphere','attach','attempt',
'attitude','available','average','aware','balance','behave','beneficial','blame','boundary','brilliant',
'campaign','candidate','capable','career','cautious','ceremony','challenge','characteristic','claim','combine');
